import Head from 'next/head';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Button from '../components/Button';

const inter = Inter({ subsets: ['latin'] });

const menuItems = [
  {
    id: 'Sign Up',
    name: 'Sign Up',
    href: '/sign-up',
  },
  {
    id: 'Sign In',
    name: 'Sign In',
    href: '/sign-in',
  },
];

export default function Home() {
const imageUrl = 'https://res.cloudinary.com/dcsuhlcmm/image/upload/';

  return (
    <>
      <Head>
        <title>Hi Street</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-[calc(100vh-0px)] relative overflow-hidden">
        <div className="absolute top-2 right-2 z-20">
          <Link href={`/auth/sign-in`}>
            <Button size="lg" appearance="homepage" type="button">
              My Account
            </Button>
          </Link>
        </div>
        <div className=" flex flex-col sm:flex-row sm:items-end mx-5  sm:mx-10 absolute z-20 top-[10%]  sm:font-normal text-white text-[2.1rem] sm:text-5xl lg:text-7xl 2xl:text-[5rem]">
          <span className="sm:pb-3">Say hi to...</span>
          <div className="flex">
            <img
              src={'/histreet-yellow-square.png'}
              alt="Hi Street"
              className="w-12 sm:w-[100px] 2xl:w-[120px]  sm:pr-4 2xl:pr-2 mr-1 sm:ml-9 sm:mr-0"
            />
            <span className=" flex items-center text-5xl sm:text-6xl lg:text-8xl 2xl:text-9xl pb-2 sm:pb-0">
              HiStreet
            </span>
          </div>
        </div>
        <h2 className="mx-5 sm:mx-10 absolute z-20 top-[27%] sm:top-[31%] 2xl:top-[27%] sm:text-2xl lg:text-3xl 2xl:text-4xl text-white ">
          Create your own, customisable, storefront for your business
        </h2>
        <h2 className="mx-5 sm:mx-10 absolute z-[70] top-[52%] sm:top-[70%] 2xl:top-[65%] sm:text-xl lg:text-2xl 2xl:text-4xl text-white bg-opacity-50 bg-black p-4 w-[83%] sm:p-8 sm:w-3/6">
          Customise your store with themes, taglines, images and more
        </h2>
        <img
          src={imageUrl + 'v1680171220/k8-wl8zWRwoQtE-unsplash_uroczd.jpg'}
          alt={'Hi Street'}
          className="sm:w-[100vw] object-cover h-[100dvh]"
        />
        <div className="absolute top-[39%] sm:top-[45%] z-20 mx-5 sm:mx-10">
          <Link href={`/auth/sign-up`}>
            <Button size="xxl" appearance="homepage" type="button">
              Sign Up Now
            </Button>
          </Link>
        </div>
        <div className="absolute top-0 bg-black bg-opacity-40 h-full w-full z-10"></div>
        <p className="absolute bottom-0 text-white text-[0.6rem]">
          Photo by Luca Vavassori on Unsplash
        </p>
        {/* <div className='absolute bottom-0 left-0'>
          <img
            src={imageUrl + 'v1680173398/custom_store3_gfooff.png'}
            alt={'red custom Store'}
            className="w-[55vw] sm:w-[30vw] 3xl:w-[30vw]  border-black border "
          />
          <img
            src={imageUrl + 'v1680173399/custom_store1_c3ujxk.png'}
            alt={'green custom Store'}
            className="w-[55vw] sm:w-[30vw] 3xl:w-[30vw]   border-black border "
          />
          <img
            src={imageUrl + 'v1680173398/custom_store2_x04cub.png'}
            alt={'blue custom Store'}
            className="w-[55vw] sm:w-[30vw] 3xl:w-[30vw]   border-black border "
          />
        </div> */}
      </div>
    </>
  );
}
