import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '../components/HomePageNavbar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hi Street</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="h-[calc(100vh-208px)] sm:h-[calc(100vh-258px)] relative overflow-hidden">
        <h1 className="px-5 sm:px-10 absolute z-20 top-[25%] font-bold sm:font-normal text-white text-3xl sm:text-6xl md:text-7xl lg:text-8xl">
          Welcome to Hi Street
        </h1>
        <h2 className="px-5 sm:px-10 absolute z-20 top-[40%] sm:text-2xl md:text-3xl lg:text-4xl text-white">
          Probably the UK's finest customisable storefront for your business
        </h2>
        <img
          src={'/k8-wl8zWRwoQtE-unsplash.jpg'}
          alt={'Hi Street'}
          className="sm:w-[100vw] object-cover h-full"
        />
        <div className="absolute top-0 bg-black bg-opacity-30 h-full w-full z-10"></div>
        <p className="absolute bottom-0 text-white text-xs sm:text-base">
          Photo by Luca Vavassori on Unsplash
        </p>
      </div>
      <div className="h-[208px] bg-gray-800"></div>
    </>
  );
}
